// Code generated by tygo. DO NOT EDIT.

//////////
// source: user.go

export interface User {
  Model: any /* gorm.Model */;
  name: string;
  birth_date?: any /* time.Time */;
  death_date?: any /* time.Time */;
  legal_domicile?: string;
  last_address?: string;
  remarks?: string;
}
