// Code generated by tygo. DO NOT EDIT.

//////////
// source: user.go

export interface User {
  Model: { ID: number; CreatedAt: string; UpdatedAt: string; DeletedAt?: string | null };
  name: string;
  birth_date?: string;
  death_date?: string;
  legal_domicile?: string;
  last_address?: string;
  remarks?: string;
}
